---
sudo: true

addons:
  apt:
    packages:
      - docker-ce
      - python
      - realpath
      - ruby

jobs:
  include:
    - stage: lint
      name: Lint text files
      language: python
      env:
        - PIP_USER=0
      install:
        - travis_retry pip install --upgrade pip
        - travis_retry ./scripts/install-text-linters.sh
      script: ./scripts/lint-text.sh --require-all
    - stage: build
      name: Test & Build
      language: go
      env:
        - RUN_TESTS=1
      script: ./scripts/container-build.sh
